import { useRef, useState } from 'react';
import { landingHeading, paletteFor } from './landingStyles';

export function ProductWalkthrough({ content, order }) {
  const [active, setActive] = useState(0);
  const dialog = useRef(null);
  const steps = content.steps;
  const stage = steps[active] ?? steps[0];
  const palette = paletteFor(content.theme);

  return <section id="preview" className={`scroll-mt-24 border-b ${palette.border} ${palette.section}`} style={{ order }}><div className="mx-auto max-w-[1400px] px-4 py-14 sm:px-6 sm:py-20 lg:px-12 lg:py-28">
    <div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-12 lg:items-end"><h2 className={`${landingHeading} lg:col-span-7 ${palette.heading}`}>{content.title}<br /><span className={palette.accent}>{content.accent}</span></h2><p className={`m-0 max-w-xl text-base leading-7 sm:text-lg sm:leading-8 lg:col-span-5 ${palette.body}`}>{content.description}</p></div>
    <div className="mx-auto mt-10 max-w-7xl sm:mt-14"><div className={`mx-auto grid max-w-2xl grid-cols-3 rounded-2xl border p-1.5 shadow-sm ${palette.surface}`} role="tablist" aria-label="Product workflow">{steps.map((item, index) => <button type="button" role="tab" key={item.title} aria-selected={active === index} aria-controls="product-preview-panel" onClick={() => setActive(index)} className={`min-h-11 rounded-xl border-0 px-2 text-xs font-semibold transition sm:text-sm ${active === index ? palette.button : `${palette.muted} hover:bg-blue-500/10`}`}><span className="hidden min-[380px]:inline">0{index + 1} · </span>{item.label ?? `Step ${index + 1}`}</button>)}</div><div className="mx-auto mt-6 max-w-3xl text-center"><h3 className={`m-0 text-xl font-semibold tracking-[-0.025em] sm:text-2xl ${palette.heading}`}>{stage.title}</h3><p className={`mx-auto mb-0 mt-2 max-w-2xl text-sm leading-6 sm:text-base sm:leading-7 ${palette.body}`}>{stage.description}</p></div><div id="product-preview-panel" role="tabpanel" className={`mt-6 overflow-hidden rounded-2xl border bg-white shadow-[0_24px_60px_-42px_rgba(15,23,42,0.45)] sm:rounded-3xl ${palette.border}`}><button type="button" className="group relative block w-full cursor-zoom-in border-0 bg-white p-0" onClick={() => dialog.current?.showModal()} aria-label={`Open ${stage.title} preview full screen`}><img key={stage.image} className="product-preview-image block h-auto w-full object-contain" src={stage.image} alt={stage.alt} width="1847" height="1015" loading="lazy" decoding="async" /><span className="absolute bottom-3 left-1/2 -translate-x-1/2 rounded-full bg-slate-950/85 px-3 py-1.5 text-[10px] font-semibold text-white shadow-lg backdrop-blur sm:hidden">Tap to enlarge</span></button></div><div className={`flex flex-col gap-3 pt-4 text-xs leading-5 sm:flex-row sm:items-center sm:justify-between ${palette.muted}`}><span><strong className={`font-semibold ${palette.heading}`}>{content.workspace_label}.</strong> {content.helper_text}</span><button type="button" className={`inline-flex min-h-11 items-center justify-center gap-2 self-start rounded-xl border px-4 font-semibold transition ${palette.secondaryButton}`} onClick={() => dialog.current?.showModal()}>{content.open_label} <span aria-hidden="true">↗</span></button></div></div>
    <dialog ref={dialog} className="fixed inset-0 m-auto max-h-[94dvh] w-[96vw] max-w-[1600px] overflow-auto rounded-2xl border border-slate-200 bg-white p-3 text-slate-950 shadow-2xl backdrop:bg-slate-950/75"><div className="mb-3 flex items-center justify-between gap-4"><p className="m-0 truncate text-sm font-semibold">{stage.title}</p><button type="button" className="min-h-11 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold hover:bg-slate-50" onClick={() => dialog.current?.close()}>Close ×</button></div><img className="block h-auto w-full rounded-xl border border-slate-200" src={stage.image} alt={stage.alt} width="1847" height="1015" loading="lazy" decoding="async" /></dialog>
  </div></section>;
}
