import { useCallback, useEffect, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { AdminShell } from '../components/admin/AdminShell';
import { useAuth } from '../context/AuthContext';
import { monitoringService } from '../services/monitoringService';

export function MonitoringPage() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  const load = useCallback(() => monitoringService.overview().then(setData).catch(() => setError('Monitoring data could not be loaded.')), []);
  useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [load]);
  if (!user?.is_admin) return <Navigate to="/dashboard" replace />;
  const summary = data?.summary;
  return <AdminShell><div className="mx-auto grid max-w-6xl gap-6"><header className="flex items-end justify-between"><div><p className="mb-2 text-xs font-semibold text-brand-600">Operations</p><h2 className="m-0 text-3xl font-semibold tracking-[-0.03em]">System monitoring</h2></div><button className="rounded-lg border border-[#D2D2D7] bg-white px-3 py-2 text-xs font-medium" onClick={load}>Refresh</button></header>
    {error ? <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p> : !summary ? <div className="h-32 animate-pulse rounded-xl bg-white" /> : <><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active users" value={summary.active_sessions} /><Metric label="Queued" value={summary.queued_analyses} /><Metric label="Running" value={summary.running_analyses} /><Metric label="Failed" value={summary.failed_analyses} /></section><section className="grid gap-4 lg:grid-cols-2"><Panel title="Provider reliability"><div className="grid gap-3">{data.providers.map((item) => <div className="flex items-center justify-between border-b border-[#ECECEF] pb-3 text-sm" key={item.provider}><span className="capitalize">{item.provider}</span><span className="tabular-nums text-[#6E6E73]">{item.failure_rate}% failed · {item.total} runs</span></div>)}</div></Panel><Panel title="Services"><div className="grid gap-3 text-sm"><Status label="API" value={data.status} /><Status label="Database" value={data.database_status} />{data.langsmith_project_url && <a className="font-medium text-brand-600" href={data.langsmith_project_url} target="_blank" rel="noreferrer">Open LangSmith traces</a>}</div></Panel></section><Panel title="Agent activity"><div className="overflow-x-auto"><table className="w-full border-collapse text-left text-xs"><thead><tr className="text-[#6E6E73]"><th className="pb-3">Agent</th><th className="pb-3 text-right">Runs</th><th className="pb-3 text-right">Failures</th><th className="pb-3 text-right">Average latency</th></tr></thead><tbody>{data.agents.map((item) => <tr className="border-t border-[#ECECEF]" key={item.agent_name}><td className="py-3">{item.agent_name.replaceAll('_', ' ')}</td><td className="py-3 text-right tabular-nums">{item.executions}</td><td className="py-3 text-right tabular-nums">{item.failures}</td><td className="py-3 text-right tabular-nums text-[#6E6E73]">{item.average_latency_ms == null ? '—' : `${Math.round(item.average_latency_ms)} ms`}</td></tr>)}</tbody></table></div></Panel><Panel title="Recent failed analyses"><div className="overflow-x-auto"><table className="w-full border-collapse text-left text-xs"><thead><tr className="text-[#6E6E73]"><th className="pb-3">Time</th><th className="pb-3">Provider</th><th className="pb-3">Error</th><th className="pb-3">Message</th></tr></thead><tbody>{data.recent_failures.map((item) => <tr className="border-t border-[#ECECEF]" key={item.id}><td className="whitespace-nowrap py-3 pr-4">{new Date(item.created_at).toLocaleString()}</td><td className="py-3 pr-4 capitalize">{item.provider}</td><td className="py-3 pr-4">{item.error_code || 'Unknown'}</td><td className="max-w-md py-3 text-[#6E6E73]">{item.error_message || 'No safe error message was recorded.'}</td></tr>)}</tbody></table>{!data.recent_failures.length && <p className="text-sm text-[#6E6E73]">No recent failures.</p>}</div></Panel></>}
  </div></AdminShell>;
}

function Metric({ label, value }) { return <article className="rounded-xl border border-[#E1E1E5] bg-white p-4"><p className="m-0 text-xs text-[#6E6E73]">{label}</p><p className="mb-0 mt-2 text-2xl font-semibold tabular-nums">{value}</p></article>; }
function Panel({ title, children }) { return <section className="rounded-xl border border-[#E1E1E5] bg-white p-5"><h2 className="mb-4 mt-0 text-sm font-semibold">{title}</h2>{children}</section>; }
function Status({ label, value }) { return <div className="flex justify-between"><span>{label}</span><span className="inline-flex items-center gap-2 capitalize text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />{value}</span></div>; }
